CREATE TABLE `users` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`username` VARCHAR(255) NOT NULL,
	`password` VARCHAR(255) NOT NULL,
	`full_name` VARCHAR(255) NOT NULL,
	`born_on` DATE NOT NULL,
	PRIMARY KEY (`id`)
)